name: .NET POM CI Pipeline

on:  
  schedule:
    - cron: '0 3 * * *'  # every day at 3 AM UTC
  pull_request: 
    branches:
      - master 
  workflow_dispatch:
  
jobs:
   build:  
    name: Build and tests 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 

    - name: Setup .NET 
      uses: actions/setup-dotnet@v1 
      with:  
        dotnet-version: '8.0.x' 
 
    - name: Install Chrome dependencies 
      run: | 
        sudo apt-get update 
        sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 
        sudo apt-get install -y google-chrome-stable 
        google-chrome --version 
        which google-chrome    

    - name: Restore dependencies 
      run: dotnet restore 
      working-directory: .

    - name: Build 
      run: dotnet build --no-restore 
      working-directory: .

    - name: Run tests 
      run: dotnet test --no-build --configuration Release  
      working-directory: . 
 
 